#set(PLATFORM_REQUIRED_DEPS NVMPI OpenGl EGL X XRandR LibDRM)
#set(PLATFORM_OPTIONAL_DEPS GLX)

#set(PLATFORM_REQUIRED_DEPS NVMPI OpenGLES EGL GBM LibInput LibDRM)
#set(APP_RENDER_SYSTEM gles)

set(PLATFORM_REQUIRED_DEPS NVMPI OpenGLES EGL X LibDRM)
set(APP_RENDER_SYSTEM gles)

list(APPEND PLATFORM_DEFINES -DPLATFORM_SETTINGS_FILE=x11.xml)

# __GBM__ is needed by eglplatform.h in case it is included before gbm.h
#list(APPEND PLATFORM_DEFINES -DMESA_EGL_NO_X11_HEADERS -D__GBM__=1 -DPLATFORM_SETTINGS_FILE=gbm.xml)

include_directories(${NVMPI_INCLUDE_DIR})
